// import box from "./data";
// let num = ;
// console.log(Math.floor(num));
// console.log();
let box = ['I hope you know CPR, because you just took my breath away!',
    'So, aside from taking my breath away, what do you do for a living?',
    'I ought to complain to Spotify for you not being named this week’s hottest single.',
    'Are you a parking ticket? ‘Cause you’ve got ‘fine’ written all over you.',
    'Your eyes are like the ocean; I could swim in them all day.',
    'When I look in your eyes, I see a very kind soul.',
    'If you were a vegetable, you’d be a ‘cute-cumber.’',
    'Do you happen to have a Band-Aid? ‘Cause I scraped my knees falling for you.',
    'I never believed in love at first sight, but that was before I saw you.',
    'I didn’t know what I wanted in a woman until I saw you.',
    'I was wondering if you could tell me: If you’re here, who’s running Heaven?',
    'No wonder the sky is gray (or dark, if at night)—all the color is in your eyes.',
    'You’ve got everything I’ve been searching for, and believe me—I’ve been looking a long time.',
    'You’re like a fine wine. The more of you I drink in, the better I feel.',
    'You’ve got a lot of beautiful curves, but your smile is absolutely my favorite.',
    'Are you as beautiful on the inside as you are on the outside?',
    'If being sexy was a crime, you’d be guilty as charged.',
    'I was wondering if you’re an artist because you were so good at drawing me in.',
    'It says in the Bible to only think about what’s pure and lovely… So I’ve been thinking about you all day long.',
    'Do you have a map? I just got lost in your eyes.',
    'I’d like to take you to the movies, but they don’t let you bring in your own snacks.',
    'You know what you would look really beautiful in? My arms.',
    'I would never play hide and seek with you because someone like you is impossible to find.',
    'Are you a magician? It’s the strangest thing, but every time I look at you, everyone else disappears.',
    'I think there’s something wrong with my phone. Could you try calling it to see if it works?',
    'Hi, I just wanted to thank you for the gift. (pause) I’ve been wearing this smile ever since you gave it to me.',
    'Are you an electrician? Because you’re definitely lighting up my day/night!',
    'I’ve heard it said that kissing is the ‘language of love.’ Would you care to have a conversation with me about it sometime?',
    'I always thought happiness started with an ‘h,’ but it turns out mine starts with ‘u.’',
    'I believe in following my dreams. Can I have your Instagram?',
    'Do you know what the Little Mermaid and I have in common? We both want to be part of your world.',
    'If you were a song, you’d be the best track on the album.',
    'On a scale of 1 to America, how free are you tonight?',
    'You know, I always thought that Disneyland was the ‘happiest place on Earth,’ but that was before I got a chance to stand here next to you.',
    'Want to go outside and get some fresh air with me? You just took my breath away.',
    'If you were a taser, you’d be set to ‘stun.’',
    'If you were a Transformer, you’d be ‘Optimu Fine.’',
    'Is your name Google? Because you have everything I’m searching for.',
    'Do you ever get tired from running through my thoughts all night?',
    'You know, they say that love is when you don’t want to sleep because reality is better than your dreams. And after seeing you, I don’t think I ever want to sleep again.',
    'Your hand looks heavy—can I hold it for you?',
    'Are you a time traveler? Because I absolutely see you in my future.',
    'Do you know what my shirt is made of? Boyfriend material.',
    'I thought this was a (bar/restaurant/etc.), but I must be in a museum because you’re a piece of art.',
    'You know, your smile has been lighting up the room all night and I just had to come and say hello.',
    'Hi, I’m (your name). Do you remember me? Oh, that’s right—we’ve only met in my dreams.',
    'What does it feel like to be the most gorgeous girl in the room?',
    'I can’t tell if that was an earthquake, or if you just seriously rocked my world.',
    'I just had to tell you, your beauty made me truly appreciate being able to see.',
    'If you were a fruit, you’d be a ‘fine-apple.’Unsplash',
    'I don’t know your name, but I’m sure it’s as beautiful as you are. I’m (your name).',
    'You are astoundingly gorgeous, but I can tell that’s the least interesting thing about you. I’d love to know more.',
    'The sparkle in your eyes is so bright, the sun must be jealous.',
    'One night I looked up at the stars and thought, ‘Wow, how beautiful.’ But now that I’m looking at you, nothing else can compare.',
    'If I had a nickel for every time I saw someone as beautiful as you, I’d still only have five cents.',
    'If beauty were time, you’d be eternity.',
    'I think the only way you could possibly be more beautiful is if I got to know you.',
    'I don’t know which is prettier today—the weather, or your eyes.',
    'I swear someone stole the stars from the sky and put them in your eyes.',
    'In my opinion, there are three kinds of beautiful: Cute, pretty, and sexy. Somehow, you manage to be all three.Cute and Cheesy Pick Up Lines for Girls',
    'I’m not usually religious, but when I saw you, I knew you were the answer to my prayers.',
    '(Hold out your hand) Hey, I’m going for a walk. Would you mind holding this for me?',
    'Do you believe in love at first sight, or should I try walking by again?',
    'I’m really glad I just bought life insurance, because when I saw you, my heart stopped.',
    'I’m not a photographer, but I can definitely picture us together.',
    'Would you mind giving me a pinch? You’re so cute, I must be dreaming.',
    'Wow, when God made you, he was seriously showing off.',
    'Excuse me, do you have the time? I just want to remember the exact minute I got a crush on you.',
    'Kiss me if I’m wrong but, dinosaurs still exist, right?',
    'If I were a cat, I’d spend all nine of my lives with you.Unsplash',
    'You know, I had a pickup line ready to go, but you’re so hot it just left my mind.',
    'When I text you goodnight later, what phone number should I use?',
    'I saw you walking by and I had to come say hello. I love your style. My name’s (your name).',
    'I’m not currently an organ donor, but I’d be happy to give you my heart.',
    'I was going to say something really sweet about you, but when I saw you, I became speechless.',
    'You know, I believe that honesty is the best policy, so to be perfectly honest, you’re the sexiest man I’ve ever seen.',
    'I’d say, ‘God bless you,’ but it looks like he already did.',
    'You must be a hell of a thief, because you managed to steal my heart from across the room.',
    'There must be something wrong with my eyes—I can’t seem to take them off of you.',
    'If you let me borrow a kiss, I promise I’ll give it right back.Best Cheesy Pick Up Lines to Use at a Bar',
    'My friends bet me I couldn’t talk to the prettiest girl in the bar. Want to use their money to buy some drinks?',
    'Trust me, I’m not drunk; I’m just intoxicated by you.',
    'I seem to have lost my number—can I have yours?',
    'I was just trying to buy a drink here, but you’re very distracting.',
    'I started reading/watching an interesting book/show last week, and I’d love to discuss it with someone. Have you heard of it?',
    'You see my friend over there? S/he wants to know if you think I’m cute.',
    'I was going to call you beautiful, but then I realized I don’t have your number yet. Them: No (or Yes)',
    'You: Are you good at math?You: Me neither (or Me too). But the only number I care about is yours.89. I’m surprised the restaurant/bar/etc. hasn’t asked you to leave yet. You’re so beautiful you’re making all the other girls look bad.',
    'Excuse me, I don’t mean to intrude, but you owe me a drink (pause), because when I saw you, I dropped mine.Unsplash',
    'Are you any good at boxing? Because you look like a knockout.92. It’s never easy meeting a complete stranger—especially one as beautiful as you—without being properly introduced. But can we try anyway?',
    'I wish I’d paid more attention to science in high school, because you and I’ve got chemistry and I want to know all about it.',
    'Hi, my name is (your name), but you can call me tonight or tomorrow.',
    'Do I know you? (pause) Oh, sorry, it’s just that you look just like my next girlfriend.',
    'If I were to ask you out on a date, would your answer be the same as the answer to this question?',
    'Hey, do you mind if we take a picture together? I just want to show my mom what my next girlfriend looks like.',
    'You look like you know how to have a good time. Been on any adventures lately?',
    'You know, I’m actually terrible at flirting. How about you try to pick me up instead?',
    'Do you have a name, or can I just call you ‘mine?’',
    'I’m not sure what it is yet, but something about you seems really interesting.',
    'If I said you had a good body would you hold it against me?',
    'Hey are you bi? because I wanna bi with you.',
    'Are you a magician? Because you just cast a spell on me.',
    'You’re my favorite YouTuber. I wanna smash your like button and subscribe for the rest of my life.',
    'Did you hurt yourself when you fell from Heaven?',
    'Are you a cat? Because you look purrrfect!',
    'Are you tired? Because you’ve been running through my mind all day.',
    'Hold out hand: “Hey I’m going for a walk. Will you hold this for me?”',
    'I’m not a photographer, but I can picture me and you together.”',
    'Are you a cake, “Because I want a piece of that.”',
    'Are you a bank loan? Well, you’ve certainly got my interest.',
    'If you were a triangle, you’d be acute one!',
    'Your hand looks heavy, let me hold it for you.',
    'I think you are suffering from a lack of Vitamin Me.',
    'On a scale of 1 to 10, you’re a 9 and I’m the 1 you lack.',
    'Do you like Harry Potter? Because I adumbledore you.',
    'Was your dad a boxer? Because damn, you’re a knockout!',
    'Your lips look lonely. Would they like to meet mine?',
    'I was wondering if you had an extra heart. Mine was just stolen.',
    'Your phone has GPS, right? Because I’m totally going to get lost in those *insert color* eyes.',
    'Would you grab my arm, so I can tell my friends I’ve been touched by an angel?',
    'Can I have your picture so I can show Santa what I want for Christmas?',
    'Your body is 65% water and I’m thirsty.',
    'Excuse me, do you have a band-aid? Cause I scraped my knee falling for you.',
    'Do I know you? Cause you look a lot like my next girlfriend/boyfriend.',
    'Do you know what my shirt is made of? Boyfriend/girlfriend material?',
    'They say Disneyland is the happiest place on earth. Well apparently, no one has ever been standing next to you.',
    'You look cold. Want to use me as a blanket?',
    'Are you an alien? Because you just abducted my heart.',
    'Did your license get suspended for driving all these guys crazy?',
    'For some reason, I was feeling a little off today. But when you came along, you definitely turned me on.',
    'Can I borrow your phone? I need to call God and tell him I’ve found his missing angel.',
    'Hey, you’re pretty and I’m cute. Together we’d be Pretty Cute.',
    'Can I follow you home? Cause my parents always told me to follow my dreams.',
    'What’s a smart, attractive man like myself doing without your phone number?',
    'I seem to have lost my phone number. Can I have yours?',
    'I’m lost. Can you give me directions to your heart?',
    'I would say God bless you, but it looks like he already did.',
    'Are you a parking ticket? Cause you’ve got fine written all over you.',
    'Is your name Google? Because you got everything I am searching for.',
    'Are you sure you’re not tired? You’ve been running through my mind all day.',
    'Did I tell you I’m writing a book? It’s a phone book and it’s missing your number.',
    'Is there an airport nearby or is it my heart taking off?',
    'Life without you would be like a broken pencil… pointless.',
    'Are you from Tennessee? Because you’re the only ten I see!',
    'I must be in a museum because you truly are a work of art.',
    'I’m not stalking you, I’m doing research!',
    'If I could rearrange the alphabet, I’d put U and I together.',
    'I’m no mathematician, but I’m pretty good with numbers. Tell you what, give me yours and watch what I can do with it.',
    'Aside from being sexy, what do you do for a living?',
    'Do you believe in love at first sight, or should I walk past again?',
    'You’re so sweet you must be made out of chocolate.',
    'I’m not good at holding conversations can I hold your hand instead',
    'Are you wi-fi? Cause I’m totally feeling a connection.',
    'If I had a nickel for every time I saw someone as beautiful as you, I’d have five cents.',
    'I’d like to take you to the movies, but they don’t let you bring in your own snacks.',
    'Are you Australian? Because you meet all of my koalafications.',
    'Know what’s on the menu? Me-N-U.',
    'Your middle name must be Gillette. Because you’re the best a man can get!',
    'You look so familiar. Didn’t we take a class together? I could’ve sworn we had chemistry.',
    'You and I are like nachos with jalapeños. I’m super cheesy, you’re super hot, and we belong together.',
    'Knock-knock. (Who’s there?) When where? (When where who?) Tomorrow night, my house, you.',
    'Do you like Star Wars? Cause Yoda only one for me.',
    'Go ahead, feel my shirt. It’s made of boyfriend material!',
    'If you were a Transformer you’d be Optimus Fine!',
    'Do you believe in love at first sight, or should I walk past you again?',
    'I’m learning about important dates in history. Wanna be one of them?',
    'I seem to have lost my phone number. Can I have yours?',
    'Are you a parking ticket? Cause you’ve got fine written all over you!',
    'Did you invent the airplane? Because you seem just Wright for me!',
    'I was wondering if you had an extra heart…because mine was just stolen.',
    'Are you Siri? Because you autocomplete me!',
    'I hope you know CPR, because you are taking my breath away!',
    'If I had four quarters to give to the four prettiest women in the world, you would have a dollar!',
    'Let me guess, your middle name is Gillette, right? Because you’re the best a man can get!',
    'Your eyes are bluer than the Atlantic Ocean, and I don’t mind being lost at sea.',
    'If you were a burger at McDonald’s, you’d be the McGorgeous.',
    'Are you a camera? Because every time I look at you, I smile.',
    'Is there an airport nearby, or was that just my heart taking off?',
    'Are you a loan? ‘Cause you’ve got my interest!',
    'I’m in the mood for pizza. A pizza you, that is!',
    'Are you a 45-degree angle? Because you’re a-cutie!',
    'You’re so sweet, you could put Hershey’s out of business!',
    'I’m good at algebra; I can replace your X and you wouldn’t need to figure out Y.',
    'I’m really glad I just bought life insurance, because when I saw you, my heart stopped.',
    'If I had to rate you from 1 to 10, I’d give you a 9, because I’m the 1 you’re missing.',
    'You must be jelly, cause jam don’t shake like that.',
    'You must be a bank loan, cause you’ve got my interest.',
    'I’ve got 1-ply, I’ve got 2-ply, but all I really want is your re-ply',
    'If nothing lasts forever, will you be my nothing?',
    'If you were a phaser on Star Trek, you’d be set to stun!',
    'Is your name Google? Because you have everything I’ve been searching for.',
    'Have you been covered in bees recently? I just assumed, because you look sweeter than honey.',
    'There must be something wrong with my eyes. I can’t take them off you.',
    'Are you from Tennessee? Because you’re the only Ten I See.',
    'You must be a campfire. Because you’re super hot and I want s’more.',
    'My buddies bet me that I wouldn’t be able to start a conversation with the most beautiful person here. How should we spend their money?',
    'Well, here I am. What are your other two wishes?',
    'Remember me? Oh, that’s right, I’ve only met you in my dreams.',
    'You must be made of cheese. Because you’re looking Gouda tonight!',
    'I’m glad I remembered to bring my library card. ‘Cause I am totally checking you out!',
    'If you were a vegetable, you would be a cute-cumber!',
    'I’m no mathematician, but I’m pretty good with numbers. Tell you what, give me yours and watch what I can do with it.',
    'Are you made of Copper and Tellurium? Cause you are CuTe.',
    'Are you an object with mass? Cuz i feel an attractive force around you.',
    'Girl are those space pants? Because your butt is out of this world!',
    'I think you’re suffering from a lack of vitamin me.',
    'Kiss me if I’m wrong, but dinosaurs still exist, right?',
    'Excuse me, is your name Earl Grey? Because you look like a hot-tea!',
    'Can I borrow a kiss? I swear I’ll give it back!',
    'If you were a vegetable you’d be a cute cumber.',
    'Is summer over? Because I’m about to “fall” for you!',
    'There’s a massive clothes sale in my bedroom – everything is 100% off',
    'I lost my number…can I have yours?',
    'Are you a baker? ‘Cause those buns look TASTY.',
    'I’m not a hoarder but I really want to keep you forever.',
    'Is your name google? Because you’re everything I’ve been searching for.',
    'Are you an onion cos I want to remove your layers.',
    'Even if there wasn’t gravity on earth, I’d still fall for you.',
    'I’m glad I brought my library card because I’m checking you out.',
    'You don’t need keys to drive me crazy.',
    'Do you know what my shirt is made of? Girlfriend material?',
    'Do you smoke pot? Because weed be cute together.',
    'Are those mirrors in your pants? Because I can see myself in them!',
    'I was wondering if you had an extra heart? Mine was just stolen.',
    'Are those space pants? Because your butt looks out of this world.',
    'Is your name Chapstick? Because you’re da-balm.',
    'Do you have a map? Because I’m getting lost in your eyes.',
    'Do you have a bandaid? Cause I hurt my knee falling for you!',
    'Are you my phone charger? Because without you, I’d die.',
    'Like a broken pencil, life without you is pointless.',
    'We’re not socks. But I think we’d make a great pair.',
    'This may be cheesy, but I think you’re grate.',
    'Did it hurt? When you fell from heaven.',
    'I wish I could select all of your clothes and press delete.',
    'If you were a booger I’d pick you first',
    'Did you sit in sugar? Because you have a sweet ass.',
    'We’re you born a mermaid, because you were a mermaid for me.',
    'Your hand looks heavy; can I hold it for you?',
    'Is your name honey? Cuz I’d love to drizzle you on my bland day.',
    'Of all the beautiful curves on your body, your smile is my favorite.',
    'I’m finding it really hard to breathe. U just keep on taking my breath away.',
    'Have you got the time… I’ve got the time if you’ve got the place!',
    'Are you glitter because you add sparkle to my life?',
    'Are you sitting on the F5 key? ‘Cause your ass is refreshing!',
    'Let’s commit the perfect crime- I’ll steal your heart, you steal mine.',
    'Do you wanna grab a coffee because I like you a latte?',
    'Hello! I guess you are looking for Mr. Right. Well, that’s me!',
    'My mom said she found a beautiful and intelligent girl for me. Is that you?',
    'How does it feel to be so gorgeous?',
    'What does it feel like to be the most beautiful girl in the room?',
    'If you were a transformer, you’d be Optimus Fine.',
    ' Do you know what’s on today’s menu? It’s Me ‘n’ U.',
    'Are you a doctor? Because my heart beats faster when I see you.',
    'Are you Australian? Because you meet all of my koalafications.',
    'Are you Space Shuttle Challenger? Cause I want to explode inside of you.',
    'Not even Fahrenheit, Celsius, or Kelvin can measure how hot you are!',
    'Let me tie your shoes, cause I don’t want you falling for anyone else.',
    'Are you an omelette? Because you’re making me egg-cited!',
    'Did you sit in a pile of sugar? Cause you have a pretty sweet butt.',
    'Do you have a pencil? Cause I want to erase your past and write our future.',
    'Are you my Appendix? Because I have a funny feeling in my stomach that makes me feel like I should take you out.',
    'Are you a florist? Cause ever since I met you, my life has been Rosey.',
    'I wanna live in your socks so I can be with you every step of the way.',
    'If God made anything more beautiful than you, I’m sure he’d keep it for himself.',
    'Do you have a map? I’m getting lost in your eyes.',
    'I don’t have a library card, but do you mind if I check you out?',
    'Are you an orphanage? Cause I wanna give you kids.',
    'Do you have a sunburn, or are you always this hot?',
    'I was feeling a little off today, but you definitely turned me on.',
    'Are you a fruit, because Honeydew you know how fine you look right now?',
    'Do you live in a corn field, cause I’m stalking you.',
    'Sorry, but you owe me a drink. [Why?] Because when I looked at you, I dropped mine.',
    'Excuse me, is your name Earl Grey? Because you look like a hot-tea!',
    'I’m not a hoarder but I really want to keep you forever.',
    'Do you have a Band-Aid? Because I just scraped my knee falling for you.',
    'Are you a parking ticket? ‘Cause you’ve got fine written all over you.',
    'Are you mexican? Because you’re my juan and only!',
    'Do you drink Pepsi? Because you’re so-da-licious!',
    'Do I know you? Cause you look exactly like my next girlfriend.',
    'I’m no organ donor but I’d be happy to give you my heart.',
    'I seem to have lost my phone number. Can I have yours?',
    'Is your nickname Chapstick? Because you’re da balm!',
    'I’m not staring at your b00bs. I’m staring at your heart.',
    'Can I take your picture to prove to all my friends that angels do exist?',
    'I’ll give up my morning cereal to spoon you instead.',
    'Do you want to see a picture of a beautiful person? (hold up a mirror)',
    'I’m not drunk, I’m just intoxicated by YOU.',
    'I was blinded by your beauty… I’m going to need your name and number for insurance purposes.',
    'Is there an airport nearby or is that just my heart taking off?',
    'There must be a lightswitch on my forehead because everytime I see you, you turn me on!',
    'Hi, I’m writing a term paper on the finer things in life, and I was wondering if I could interview you?',
    'Have you been to the doctor lately? Cause I think you’re lacking some Vitamin Me.',
    'Can I follow you home? Cause my parents always told me to follow my dreams.',
    'You look so familiar… didn’t we take a class together? I could’ve sworn we had chemistry.',
    'Hi, I’m Mr. Right. Someone said you were looking for me?',
    'Do you like Nintendo? Because Wii would look good together.',
    'If you were a flower you’d be a damnnn-delion',
    'If you were ground coffee, you’d be Espresso cause you’re so fine.',
    'If I had a star for every time you brightened my day, I’d have a galaxy in my hand.',
    'Damn, if being sexy was a crime, you’d be guilty as charged!',
    'I was wondering if you had an extra heart? Mine seems to have been stolen',
    'Do you smoke pot? Because weed be cute together.',
    'I thought happiness started with an H. Why does mine start with U?',
    'Are you a campfire? Cause you are hot and I want s’more.',
    'If you were a tropical fruit, you’d be a Fine-apple!',
    'Are you a banana? Because I find you a-peeling',
    'If we fight, I think you would be the one giving the final blow.'
];

// console.log(box);
function clickMe() {
    document.getElementById('btn').style.display = 'inline';
    document.getElementById('cont').style.border = 'black 1px solid';
    let ran = document.getElementById('cont').innerHTML = `${box[Math.floor(Math.random() * 306)]}`;
    // document.getElementById('cont').innerHTML = `${ran}`;
    console.log(box[Math.floor(Math.random() * 98)]);
}
function copyToClip() {
    let copyText = document.getElementById('cont').innerText;
    console.log(copyText);
    navigator.clipboard.writeText(`${copyText}`);
    alert('COPIED TO CLIPBOARD!!')
}